export const BRAND = {
  primaryDark: '#7B542F',
  primaryMedium: '#B6771D',
  primaryAccent: '#FF9D00',
  primaryLight: '#FFCF71',
};

export const COLORS = {
  primary: BRAND.primaryMedium,
  accent: BRAND.primaryAccent,
  background: BRAND.primaryLight,
  surface: '#FFFFFF',
  surfaceSoft: '#F6E7CC',
  surfaceMuted: '#F8F1E5',
  surfaceSubtle: '#F4E8D7',
  surfaceRaised: '#EFE0CC',
  surfaceInfo: '#EDF3FB',
  surfaceSuccess: '#E8F6ED',
  surfaceWarning: '#FFF3D9',
  surfaceDanger: '#FCEAF0',
  textPrimary: BRAND.primaryDark,
  textSecondary: BRAND.primaryMedium,
  textMuted: '#8A6540',
  textSuccess: '#1F6D3D',
  textWarning: '#8A5E10',
  textDanger: '#9B2F45',
  border: '#D2B088',
  borderSoft: '#D9C2A0',
  borderInfo: '#C8D8EB',
  borderSuccess: '#B7D8C1',
  borderWarning: '#E5C98F',
  borderDanger: '#E3B7C1',
  borderStrong: BRAND.primaryMedium,
  onAccent: BRAND.primaryDark,
  danger: '#A53A49',
  textOnPrimary: '#FFFFFF',
  shadow: '#A8773A',
  placeholder: '#A47A50',
  sidebarBackground: BRAND.primaryDark,
  sidebarText: BRAND.primaryLight,
  sidebarActiveBackground: BRAND.primaryMedium,
  sidebarActiveText: '#FFFFFF',
};

export const DARK_COLORS = {
  primary: BRAND.primaryLight,
  accent: BRAND.primaryAccent,
  background: BRAND.primaryDark,
  surface: BRAND.primaryMedium,
  textPrimary: '#FFFFFF',
  textSecondary: BRAND.primaryLight,
  textMuted: '#E7BF78',
  border: '#C6924B',
};
